### ISSUE TITLE
Passer à Django 1.11

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4811]
Actuellement, le site est sur Django 1.10. Il faudrait que nous passions à la version 1.11 afin d'obtenir un support étendu (c'est une LTS) et de ne pas prendre de retard pour la suite.

- [Doc sur les mises à jour](https://docs.djangoproject.com/fr/1.11/howto/upgrade-version/)
- [Notes de version 1.11](https://docs.djangoproject.com/en/dev/releases/1.11/)

**Comment by rezemika** [comment]
J'ai fais une petite tentative de mon côté, et il y a plein de Warnings que je ne saurais résoudre.

J'ai juste résolu quelques erreurs, je mets les solutions ici si ça peut aider quelqu'un.

Le fichier https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/date.py devient : voir #4815.

Cette ligne (https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L5) devient : `from django.db import DatabaseError`.

Voilà les principaux Warnings qui sortent pendant les tests : 

- `WARNING zds.utils.models User #1 failed to use hat #None.` Même erreur 6 fois pour l'utilisateur n°2.
- `/python3.5/site-packages/django/core/paginator.py:112: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <QuerySet [<UserGallery: Galerie « titre de la gallerie 23 » de firm310>]>`
- `WARNING zds.member.views ValueError: modifying karma failed because Max karma amount has to be between -100 and 100, you entered 420`
- `WARNING zds.member.views ValueError: modifying karma failed because note cannot be empty`
- `WARNING zds.tutorialv2.utils could not remove store path /home/rezemika/zds/zds-site/contents-public-test/reiciendis-sequi-vel-facere-et-ratione__building/extra_contents/images/test.png`
- Une stacktrace qui apparait plusieurs fois de suite : 

```
WARNING:root:Could not resolve form field 'text'.
Traceback (most recent call last):
  File "/home/rezemika/zds/dj2venv/lib/python3.5/site-packages/crispy_forms/utils.py", line 92, in render_field
    field_instance = form.fields[field]
KeyError: 'text'
```
